# Generated by Django 5.1.1 on 2026-02-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRawTW',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('quarter', models.IntegerField()),
                ('statement_type', models.CharField(max_length=10)),
                ('item_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=32)),
            ],
            options={
                'verbose_name': 'TW Financial Raw',
                'verbose_name_plural': 'TW Financial Raw Data',
                'db_table': 'financial_raw_tw',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialRawUS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('quarter', models.IntegerField()),
                ('statement_type', models.CharField(max_length=10)),
                ('item_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=32)),
            ],
            options={
                'verbose_name': 'US Financial Raw',
                'verbose_name_plural': 'US Financial Raw Data',
                'db_table': 'financial_raw_us',
                'managed': False,
            },
        ),
    ]
