// Copyright 2026 ting-yu-hsu. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newMediaGetNewsListByCategoryCmd(flags *rootFlags) *cobra.Command {
	var flagLimit int
	var flagPage string
	var flagStartAt int
	var flagEndAt int
	var flagStock string
	var flagKeyword string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "get-news-list-by-category <categoryId>",
		Aliases:     []string{"get"},
		Short:       "取得鉅亨網的新聞列表，支援多種分類： - `headline` (頭條新聞) - `tw_stock` (台股新聞) -...",
		Example:     "  cnyes-cli-pp-cli media get-news-list-by-category 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "media.get-news-list-by-category", "pp:method": "GET", "pp:path": "/media/api/v1/newslist/category/{categoryId}", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/media/api/v1/newslist/category/{categoryId}"
			path = replacePathParam(path, "categoryId", args[0])
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "media", path, map[string]string{
				"limit":   fmt.Sprintf("%v", flagLimit),
				"page":    fmt.Sprintf("%v", flagPage),
				"startAt": fmt.Sprintf("%v", flagStartAt),
				"endAt":   fmt.Sprintf("%v", flagEndAt),
				"stock":   fmt.Sprintf("%v", flagStock),
				"keyword": fmt.Sprintf("%v", flagKeyword),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().IntVar(&flagLimit, "limit", 30, "每頁顯示的新聞筆數 (預設 30)")
	cmd.Flags().StringVar(&flagPage, "page", "1", "頁碼")
	cmd.Flags().IntVar(&flagStartAt, "start-at", 0, "開始時間戳記 (Epoch seconds)")
	cmd.Flags().IntVar(&flagEndAt, "end-at", 0, "結束時間戳記 (Epoch seconds)")
	cmd.Flags().StringVar(&flagStock, "stock", "", "股票代號 (例如：2330)")
	cmd.Flags().StringVar(&flagKeyword, "keyword", "", "關鍵字搜尋")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
