// Copyright 2026 ting-yu-hsu. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newMacrotrendsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "macrotrends",
		Short: "Manage macrotrends",
	}

	cmd.AddCommand(newMacrotrendsGetFinancialsCmd(flags))
	cmd.AddCommand(newMacrotrendsGetRatiosCmd(flags))
	return cmd
}
