// Copyright 2026 ting-yu-hsu. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newMacrotrendsGetRatiosCmd(flags *rootFlags) *cobra.Command {
	var flagSymbol string
	var flagType string

	cmd := &cobra.Command{
		Use:         "get-ratios",
		Short:       "取得指定美股的本益比、股價淨值比、債務股本比與利潤率等財務比率歷史數據。",
		Example:     "  macrotrends-pp-cli macrotrends get-ratios --symbol example-value --type example-value",
		Annotations: map[string]string{"pp:endpoint": "macrotrends.get-ratios", "pp:method": "GET", "pp:path": "/api/macrotrends/ratios", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("symbol") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "symbol")
			}
			if !cmd.Flags().Changed("type") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "type")
			}
			if cmd.Flags().Changed("type") {
				allowedType := []string{"pe-ratio", "price-book", "debt-equity", "margins"}
				validType := false
				for _, v := range allowedType {
					if flagType == v {
						validType = true
						break
					}
				}
				if !validType {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "type", flagType, allowedType)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/macrotrends/ratios"
			params := map[string]string{}
			if flagSymbol != "" {
				params["symbol"] = fmt.Sprintf("%v", flagSymbol)
			}
			if flagType != "" {
				params["type"] = fmt.Sprintf("%v", flagType)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "macrotrends", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagSymbol, "symbol", "", "美股股票代號 (例如: AAPL)")
	cmd.Flags().StringVar(&flagType, "type", "", "比率類型 (pe-ratio, price-book, debt-equity, margins) (one of: pe-ratio, price-book, debt-equity, margins)")

	return cmd
}
