// Copyright 2026 ting-yu-hsu. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type MediaGetNewsListByCategoryResponse struct {
	Items      json.RawMessage `json:"items"`
	Message    string          `json:"message"`
	StatusCode int             `json:"statusCode"`
}

type MediaGetNewsListBySymbolResponse struct {
	Items      json.RawMessage `json:"items"`
	Message    string          `json:"message"`
	StatusCode int             `json:"statusCode"`
}
