# Generated by Django 5.1.1 on 2026-02-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChipData',
            fields=[
                ('date', models.DateField(db_column='日期')),
                ('number', models.CharField(db_column='number', max_length=20, primary_key=True, serialize=False)),
                ('foreign_buy', models.BigIntegerField(blank=True, db_column='外陸資買進股數(不含外資自營商)', null=True)),
                ('foreign_sell', models.BigIntegerField(blank=True, db_column='外陸資賣出股數(不含外資自營商)', null=True)),
                ('foreign_net', models.BigIntegerField(blank=True, db_column='外陸資買賣超股數(不含外資自營商)', null=True)),
                ('trust_buy', models.BigIntegerField(blank=True, db_column='投信買進股數', null=True)),
                ('trust_sell', models.BigIntegerField(blank=True, db_column='投信賣出股數', null=True)),
                ('trust_net', models.BigIntegerField(blank=True, db_column='投信買賣超股數', null=True)),
                ('dealer_net', models.BigIntegerField(blank=True, db_column='自營商買賣超股數', null=True)),
                ('total_net', models.BigIntegerField(blank=True, db_column='三大法人買賣超股數', null=True)),
            ],
            options={
                'verbose_name': 'Chip Data',
                'verbose_name_plural': 'Chip Data',
                'db_table': 'stock_investor',
                'managed': False,
            },
        ),
    ]
