# Generated by Django 5.1.1 on 2026-02-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValuationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('market', models.CharField(choices=[('TW', 'Taiwan'), ('US', 'USA')], max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('method', models.CharField(choices=[('DCF', 'Discounted Cash Flow'), ('PE', 'P/E Ratio Model'), ('PB', 'P/B Ratio Model'), ('GRAHAM', 'Graham Number')], max_length=20)),
                ('fair_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('upside', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage upside (e.g. 0.20 for 20%)', max_digits=10, null=True)),
                ('assumptions', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'symbol'],
                'indexes': [models.Index(fields=['symbol', 'market', 'method'], name='valuation_v_symbol_d68b92_idx')],
            },
        ),
    ]
