# Generated by Django 6.0.4 on 2026-06-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=10)),
                ('symbol', models.CharField(max_length=20)),
                ('pe', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('pb', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stock_metrics',
                'indexes': [models.Index(fields=['market', 'symbol'], name='stock_metri_market_b2471a_idx')],
                'unique_together': {('market', 'symbol')},
            },
        ),
    ]
