# Generated by Django 6.0.4 on 2026-07-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0002_stockmetrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=10)),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('master_name', models.CharField(max_length=50)),
                ('rank', models.IntegerField()),
                ('close_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('roe', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('gross_margin', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('debt_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('net_income_growth', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'master_selection',
                'ordering': ['market', 'master_name', 'rank'],
                'unique_together': {('market', 'master_name', 'symbol')},
            },
        ),
    ]
