# Generated by Django 6.0.4 on 2026-09-10 19:07

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0003_masterselection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuationAssumptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('market', models.CharField(choices=[('TW', 'Taiwan'), ('US', 'USA')], max_length=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_date', models.DateField(help_text='SCD2 生效起始日期')),
                ('end_date', models.DateField(blank=True, help_text='SCD2 生效結束日期（最新版本為 NULL）', null=True)),
                ('is_current', models.BooleanField(db_index=True, default=True, help_text='是否為當前最新有效版本')),
                ('assumptions', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='估值假設快照 (wacc, g, roic, tax_rate, margin, etc.)')),
                ('valuation_snapshot', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='當期估值結果快照 (dcf_per_share, fair_value, ev, net_debt, etc.)')),
                ('change_reason', models.CharField(blank=True, default='', help_text='版本變更原因 (例如：季報更新、分析師調校、批量重算)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'valuation_assumption_history',
                'ordering': ['-version', '-effective_date'],
                'indexes': [models.Index(fields=['symbol', 'market', 'is_current'], name='valuation_a_symbol_d478fb_idx'), models.Index(fields=['symbol', 'market', 'version'], name='valuation_a_symbol_f2eb7b_idx'), models.Index(fields=['effective_date'], name='valuation_a_effecti_497884_idx')],
            },
        ),
    ]
