# Generated by Django 6.0.4 on 2026-09-10 19:33

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0004_valuationassumptionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuationassumptionhistory',
            name='flag_reasons',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='異常原因標籤列表'),
        ),
        migrations.AddField(
            model_name='valuationassumptionhistory',
            name='is_flagged',
            field=models.BooleanField(db_index=True, default=False, help_text='是否包含異常參數標記'),
        ),
        migrations.AddField(
            model_name='valuationresult',
            name='flag_reason',
            field=models.TextField(blank=True, default='', help_text='異常原因或防護備註'),
        ),
        migrations.AddField(
            model_name='valuationresult',
            name='is_flagged',
            field=models.BooleanField(db_index=True, default=False, help_text='是否觸發異常防護閥 (如 WACC 超出 [3%, 20%] 等)'),
        ),
    ]
