# Generated by Django 6.0.4 on 2026-06-24 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecFilingIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cik', models.CharField(max_length=20)),
                ('ticker', models.CharField(blank=True, max_length=20, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('form_type', models.CharField(max_length=20)),
                ('accession_no', models.CharField(max_length=30, unique=True)),
                ('filing_date', models.DateField()),
                ('period_of_report', models.DateField(blank=True, null=True)),
                ('primary_doc_url', models.TextField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sec_filing_index',
                'indexes': [models.Index(fields=['cik', 'form_type'], name='sec_filing__cik_9d19a5_idx'), models.Index(fields=['ticker', 'form_type'], name='sec_filing__ticker_5278a9_idx'), models.Index(fields=['filing_date'], name='sec_filing__filing__e47562_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecFinancialXbrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('cik', models.CharField(blank=True, max_length=20, null=True)),
                ('period_end', models.DateField()),
                ('fiscal_year', models.IntegerField()),
                ('fiscal_quarter', models.IntegerField()),
                ('concept', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=4, max_digits=32)),
                ('unit', models.CharField(default='USD', max_length=50)),
                ('form_type', models.CharField(blank=True, max_length=10, null=True)),
                ('accession_no', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sec_financial_xbrl',
                'indexes': [models.Index(fields=['ticker', 'fiscal_year', 'fiscal_quarter'], name='sec_financi_ticker_743e69_idx'), models.Index(fields=['concept'], name='sec_financi_concept_b9f6aa_idx')],
                'unique_together': {('ticker', 'period_end', 'concept', 'form_type')},
            },
        ),
        migrations.CreateModel(
            name='SecInsiderTrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cik', models.CharField(max_length=20)),
                ('ticker', models.CharField(max_length=20)),
                ('insider_name', models.CharField(max_length=255)),
                ('insider_title', models.CharField(blank=True, max_length=255, null=True)),
                ('is_senior_officer', models.BooleanField(default=False)),
                ('transaction_date', models.DateField()),
                ('transaction_code', models.CharField(max_length=5)),
                ('transaction_type', models.CharField(blank=True, max_length=50, null=True)),
                ('shares', models.BigIntegerField(default=0)),
                ('price_per_share', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('shares_owned_after', models.BigIntegerField(blank=True, null=True)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(default='pp-edgar', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sec_insider_trades',
                'indexes': [models.Index(fields=['ticker', 'transaction_date'], name='sec_insider_ticker_6eb49e_idx'), models.Index(fields=['transaction_code'], name='sec_insider_transac_b96202_idx'), models.Index(fields=['is_senior_officer', 'ticker'], name='sec_insider_is_seni_92889c_idx')],
                'unique_together': {('ticker', 'insider_name', 'transaction_date', 'transaction_code', 'shares')},
            },
        ),
        migrations.CreateModel(
            name='Sec13fHoldings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cik', models.CharField(max_length=20)),
                ('ticker', models.CharField(blank=True, max_length=20, null=True)),
                ('cusip', models.CharField(blank=True, max_length=9, null=True)),
                ('security_name', models.CharField(blank=True, max_length=255, null=True)),
                ('shares', models.BigIntegerField(default=0)),
                ('value_usd', models.BigIntegerField(default=0)),
                ('put_call', models.CharField(blank=True, default='', max_length=10)),
                ('investment_discretion', models.CharField(blank=True, max_length=20, null=True)),
                ('period_of_report', models.DateField()),
                ('prev_shares', models.BigIntegerField(blank=True, null=True)),
                ('shares_change', models.BigIntegerField(blank=True, null=True)),
                ('change_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('action_type', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='sec_edgar.secfilingindex')),
            ],
            options={
                'db_table': 'sec_13f_holdings',
                'indexes': [models.Index(fields=['cik', 'period_of_report'], name='sec_13f_hol_cik_9d72de_idx'), models.Index(fields=['ticker', 'period_of_report'], name='sec_13f_hol_ticker_4bb27b_idx'), models.Index(fields=['cusip'], name='sec_13f_hol_cusip_8685fb_idx')],
                'unique_together': {('filing', 'cusip', 'put_call')},
            },
        ),
    ]
