// Copyright 2026 ting-yu-hsu. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type QuoteHtmlWebserviceGetQuotesResponse struct {
	FormattedQuoteResult json.RawMessage `json:"FormattedQuoteResult"`
}

type RsGetNewsFeedResponse struct {
}

type RsSearchNewsResponse struct {
}
