// Copyright 2026 ting-yu-hsu. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

type FinancialRecord struct {
	Amount        float64 `json:"amount"`
	ItemName      string  `json:"item_name"`
	Quarter       int     `json:"quarter"`
	StatementType string  `json:"statement_type"`
	Symbol        string  `json:"symbol"`
	Year          int     `json:"year"`
}

type RatioRecord struct {
	Date      string  `json:"date"`
	RatioName string  `json:"ratio_name"`
	Symbol    string  `json:"symbol"`
	Value     float64 `json:"value"`
}
