// Copyright 2026 ting-yu-hsu. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newQuoteHtmlWebservicePromotedCmd(flags *rootFlags) *cobra.Command {
	var flagSymbols string
	var flagRequestMethod string
	var flagOutput string

	cmd := &cobra.Command{
		Use:         "quote-html-webservice",
		Short:       "取得 Dow Jones (.DJI)、S&P 500 (.SPX)、Nasdaq (.IXIC) 等主要指數或個股 (AAPL, NVDA, TSLA) 之即時行情。",
		Long:        "Shortcut for 'quote-html-webservice get-quotes'. 取得 Dow Jones (.DJI)、S&P 500 (.SPX)、Nasdaq (.IXIC) 等主要指數或個股 (AAPL, NVDA, TSLA) 之即時行情。",
		Example:     "  cnbc-cli-pp-cli quote-html-webservice --symbols example-value",
		Annotations: map[string]string{"pp:endpoint": "quote-html-webservice.get-quotes", "pp:method": "GET", "pp:path": "https://quote.cnbc.com/quote-html-webservice/restQuote/symbolType/symbol", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "https://quote.cnbc.com/quote-html-webservice/restQuote/symbolType/symbol"
			params := map[string]string{}
			if flagSymbols != "" {
				params["symbols"] = fmt.Sprintf("%v", flagSymbols)
			}
			if flagRequestMethod != "" {
				params["requestMethod"] = fmt.Sprintf("%v", flagRequestMethod)
			}
			if flagOutput != "" {
				params["output"] = fmt.Sprintf("%v", flagOutput)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "quote-html-webservice", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagSymbols, "symbols", ".DJI|.SPX|.IXIC", "查詢代碼清單，多檔以垂直線分隔 (例如 `.DJI|.SPX|.IXIC` 或 `AAPL|NVDA|TSLA`)")
	cmd.Flags().StringVar(&flagRequestMethod, "request-method", "itv", "請求模式 (預設 itv)")
	cmd.Flags().StringVar(&flagOutput, "output", "json", "輸出格式 (預設 json)")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
