// Copyright 2026 ting-yu-hsu. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newRsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "rs",
		Short:  "Manage rs",
		Hidden: true,
	}

	cmd.AddCommand(newRsGetNewsFeedCmd(flags))
	cmd.AddCommand(newRsSearchNewsCmd(flags))
	return cmd
}
