// Copyright 2026 ting-yu-hsu. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newRsSearchNewsCmd(flags *rootFlags) *cobra.Command {
	var flagKeywords string
	var flagSort string
	var flagPartnerId string

	cmd := &cobra.Command{
		Use:         "search-news",
		Short:       "依關鍵字搜尋 CNBC 新聞文章與報導。",
		Example:     "  cnbc-cli-pp-cli rs search-news --keywords your-token-here",
		Annotations: map[string]string{"pp:endpoint": "rs.search-news", "pp:method": "GET", "pp:path": "/rs/search/all/view.xml", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("keywords") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "keywords")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/rs/search/all/view.xml"
			params := map[string]string{}
			if flagKeywords != "" {
				params["keywords"] = fmt.Sprintf("%v", flagKeywords)
			}
			if flagSort != "" {
				params["sort"] = fmt.Sprintf("%v", flagSort)
			}
			if flagPartnerId != "" {
				params["partnerId"] = fmt.Sprintf("%v", flagPartnerId)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "rs", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagKeywords, "keywords", "", "搜尋關鍵字 (例如 fed, inflation, nvidia)")
	cmd.Flags().StringVar(&flagSort, "sort", "date", "排序方式 (date 或 relevance)")
	cmd.Flags().StringVar(&flagPartnerId, "partner-id", "wrss01", "合作夥伴識別碼 (預設 wrss01)")

	return cmd
}
