# Generated by Django 5.1.1 on 2026-02-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPriceTW',
            fields=[
                ('number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(db_column='Date')),
                ('open', models.FloatField(blank=True, db_column='Open', null=True)),
                ('high', models.FloatField(blank=True, db_column='High', null=True)),
                ('low', models.FloatField(blank=True, db_column='Low', null=True)),
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('volume', models.BigIntegerField(blank=True, db_column='Volume', null=True)),
            ],
            options={
                'verbose_name': 'TW Daily Price',
                'verbose_name_plural': 'TW Daily Prices',
                'db_table': 'stock_cost',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DailyPriceUS',
            fields=[
                ('number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(db_column='Date')),
                ('open', models.FloatField(blank=True, db_column='Open', null=True)),
                ('high', models.FloatField(blank=True, db_column='High', null=True)),
                ('low', models.FloatField(blank=True, db_column='Low', null=True)),
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('volume', models.BigIntegerField(blank=True, db_column='Volume', null=True)),
            ],
            options={
                'verbose_name': 'US Daily Price',
                'verbose_name_plural': 'US Daily Prices',
                'db_table': 'stock_cost_us',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockTW',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('market', models.CharField(blank=True, max_length=20, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Taiwan Stock',
                'verbose_name_plural': 'Taiwan Stocks',
                'db_table': 'stocks_tw',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockUS',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('market', models.CharField(blank=True, max_length=20, null=True)),
                ('cik', models.CharField(blank=True, max_length=20, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'US Stock',
                'verbose_name_plural': 'US Stocks',
                'db_table': 'stocks_us',
                'managed': False,
            },
        ),
    ]
