# Generated by Django 6.0.4 on 2026-07-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroTW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('metric', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TW Macro Data',
                'verbose_name_plural': 'TW Macro Data',
                'db_table': 'macro_data_tw',
                'managed': True,
                'unique_together': {('date', 'metric')},
            },
        ),
        migrations.CreateModel(
            name='MacroUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('metric', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'US Macro Data',
                'verbose_name_plural': 'US Macro Data',
                'db_table': 'macro_data_us',
                'managed': True,
                'unique_together': {('date', 'metric')},
            },
        ),
    ]
